require("nvim-treesitter").setup()
require("nvim-treesitter").install({
    "bash",
    "c",
    "cpp",
    "css",
    "dockerfile",
    "go",
    "html",
    "javascript",
    "json",
    "lua",
    "python",
    "rust",
    "typescript",
    "yaml",
})
