name: macOS
run-name: macOS
on: [push, pull_request]

jobs:
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run script
        run: ${GITHUB_WORKSPACE}/run_once_install.sh

